
:queues:
  - default
 # - mailers

:schedule:
  renew_contract_job:
    cron: '* * * * *'
    class: RenewContractJob

#  re_confirmation_space_request_job:
#    cron: '* * * * *'
#    class: ReConfirmationSpaceRequestJob