
:queues:
  - default
  - mailers

:schedule:
  renew_contract_job:
    cron: '*/5 * * * *'
    class: RenewContractJob

  re_confirmation_space_request_job:
    cron: '*/5 * * * *'
    class: ReConfirmationSpaceRequestJob